version: '3.4'
services:
  db:
    image: postgres:12-alpine
    container_name: kenji_db
    ports:
      - 5432:6432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: portal